### ISSUE TITLE
Curly brackets in tag attributes

### ISSUE THREAD

**Issue by kulesa** [tj/haml.js#30]
Hi! I have problem with curly brackets in tag attribute. I am trying to add this line to layout

```
    %script{ type: "text/javascript", src: "http://www.google.com/jsapi?autoload={'modules':[{name:'maps',version:3,other_params:'sensor=false'}]}"}
```

and getting this exception 

```
    :SyntaxError: (Haml): Unexpected token ]
    at Function (unknown source)
    at lib/haml.js:651:14
    at Object.render (lib/haml.js:665:6)
```

Is there any way to escape the closing bracket?

**Comment by tj** [comment]
not currently no, maybe try urlencoding those chars

**Comment by kulesa** [comment]
Thanks, this worked fine: 

```
     %script{ type: "text/javascript", src: "http://www.google.com/jsapi?autoload={'modules':[{name:'maps',version:3,other_params:'sensor=false'" + decodeURI("%7d") +  "]" + decodeURI("%7d")}
```
