### ISSUE TITLE
%div{ class: "#{classes} anotherClass" } doesn't work

### ISSUE THREAD

**Issue by sanchan** [tj/haml.js#68]
I want to render a variable inside of an string attribute, but I can't :(

I'm avoiding this sending the complete text from my view, like:
classes += " anotherClass";

so I can do:
%div{ class: classes }
wich works well :)

Thanks!

/Users/sanchan/hamljs_debug/node_modules/hamljs/lib/haml.js:674
      throw err
            ^
SyntaxError: (page.haml): Unexpected token ILLEGAL
    at Function (<anonymous>)
    at /Users/sanchan/hamljs_debug/node_modules/hamljs/lib/haml.js:662:14
    at Object.HAML.render (/Users/sanchan/hamljs_debug/node_modules/hamljs/lib/haml.js:676:6)
    at Object.<anonymous> (/Users/sanchan/hamljs_debug/app.js:27:58)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

**Comment by sanchan** [comment]
I just figured out that the way to get what I want is writing this:

> %div{ class: classes + " anotherClass" }
